# Web server config
quarkus.http.port=8080

# Logging config
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."org.tugboat".level=DEBUG

# --- Tugboat Custom Properties ---
tugboat.harbor.url=harbor.local
tugboat.harbor.project=maven-proxy
# Dev purposes only, in production you should use Kubernetes secrets
tugboat.harbor.username=robot\$tugboat
tugboat.harbor.password=sw4t72ka9erdgDl14turh0OCPu9boFfl

# --- NATS Configuration ---
quarkus.messaging.nats.connection.servers=nats://localhost:4222
# Enable JetStream connector for the outbound topic
mp.messaging.outgoing.artifact-downloads.connector=quarkus-jetstream
# The name of the JetStream where messages will be persisted
mp.messaging.outgoing.artifact-downloads.stream=tugboat-events
# The subject (routing key) inside the stream
mp.messaging.outgoing.artifact-downloads.subject=artifact-downloads