# Web server config for publisher (avoids port collision with the gateway)
quarkus.http.port=8081

# Harbor Auth (Consider using ENV variables in prod)
tugboat.harbor.url=harbor.local
tugboat.harbor.username=robot$tugboat
tugboat.harbor.password=sw4t72ka9erdgDl14turh0OCPu9boFfl


# --- NATS JetStream Configuration (PUBLISHER - CONSUMER) ---
quarkus.messaging.nats.connection.servers=nats://localhost:4222

# 1. Define the Stream
quarkus.messaging.nats.streams.tugboat-events.configuration.subjects=artifact-downloads
quarkus.messaging.nats.streams.tugboat-events.configuration.storage-type=file

# 2. Define the Durable Pull Consumer (Notice the updated syntax here)
quarkus.messaging.nats.streams.tugboat-events.pull-consumers.artifact-downloads.consumer-configuration.filter-subjects=artifact-downloads
quarkus.messaging.nats.streams.tugboat-events.pull-consumers.artifact-downloads.consumer-configuration.deliver-policy=all

# 3. Configure the INCOMING channel
mp.messaging.incoming.artifact-downloads.connector=quarkus-jetstream
mp.messaging.incoming.artifact-downloads.stream=tugboat-events
mp.messaging.incoming.artifact-downloads.consumer=artifact-downloads

